//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UsuarioCRUD.WSArea {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://calculadora.service.ed.com/", ConfigurationName="WSArea.CalculadoraArea")]
    public interface CalculadoraArea {
        
        // CODEGEN: Generating message contract since message part namespace () does not match the default value (http://calculadora.service.ed.com/)
        [System.ServiceModel.OperationContractAttribute(Action="http://calculadora.service.ed.com/CalculadoraArea/AreaCuadradoRequest", ReplyAction="http://calculadora.service.ed.com/CalculadoraArea/AreaCuadradoResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        UsuarioCRUD.WSArea.AreaCuadradoResponse AreaCuadrado(UsuarioCRUD.WSArea.AreaCuadradoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://calculadora.service.ed.com/CalculadoraArea/AreaCuadradoRequest", ReplyAction="http://calculadora.service.ed.com/CalculadoraArea/AreaCuadradoResponse")]
        System.Threading.Tasks.Task<UsuarioCRUD.WSArea.AreaCuadradoResponse> AreaCuadradoAsync(UsuarioCRUD.WSArea.AreaCuadradoRequest request);
        
        // CODEGEN: Generating message contract since message part namespace () does not match the default value (http://calculadora.service.ed.com/)
        [System.ServiceModel.OperationContractAttribute(Action="http://calculadora.service.ed.com/CalculadoraArea/AreaRectanguloRequest", ReplyAction="http://calculadora.service.ed.com/CalculadoraArea/AreaRectanguloResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        UsuarioCRUD.WSArea.AreaRectanguloResponse AreaRectangulo(UsuarioCRUD.WSArea.AreaRectanguloRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://calculadora.service.ed.com/CalculadoraArea/AreaRectanguloRequest", ReplyAction="http://calculadora.service.ed.com/CalculadoraArea/AreaRectanguloResponse")]
        System.Threading.Tasks.Task<UsuarioCRUD.WSArea.AreaRectanguloResponse> AreaRectanguloAsync(UsuarioCRUD.WSArea.AreaRectanguloRequest request);
        
        // CODEGEN: Generating message contract since message part namespace () does not match the default value (http://calculadora.service.ed.com/)
        [System.ServiceModel.OperationContractAttribute(Action="http://calculadora.service.ed.com/CalculadoraArea/AreaTrianguloRequest", ReplyAction="http://calculadora.service.ed.com/CalculadoraArea/AreaTrianguloResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        UsuarioCRUD.WSArea.AreaTrianguloResponse AreaTriangulo(UsuarioCRUD.WSArea.AreaTrianguloRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://calculadora.service.ed.com/CalculadoraArea/AreaTrianguloRequest", ReplyAction="http://calculadora.service.ed.com/CalculadoraArea/AreaTrianguloResponse")]
        System.Threading.Tasks.Task<UsuarioCRUD.WSArea.AreaTrianguloResponse> AreaTrianguloAsync(UsuarioCRUD.WSArea.AreaTrianguloRequest request);
        
        // CODEGEN: Generating message contract since message part namespace () does not match the default value (http://calculadora.service.ed.com/)
        [System.ServiceModel.OperationContractAttribute(Action="http://calculadora.service.ed.com/CalculadoraArea/AreaCirculoRequest", ReplyAction="http://calculadora.service.ed.com/CalculadoraArea/AreaCirculoResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        UsuarioCRUD.WSArea.AreaCirculoResponse AreaCirculo(UsuarioCRUD.WSArea.AreaCirculoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://calculadora.service.ed.com/CalculadoraArea/AreaCirculoRequest", ReplyAction="http://calculadora.service.ed.com/CalculadoraArea/AreaCirculoResponse")]
        System.Threading.Tasks.Task<UsuarioCRUD.WSArea.AreaCirculoResponse> AreaCirculoAsync(UsuarioCRUD.WSArea.AreaCirculoRequest request);
        
        // CODEGEN: Generating message contract since element name name from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://calculadora.service.ed.com/CalculadoraArea/helloRequest", ReplyAction="http://calculadora.service.ed.com/CalculadoraArea/helloResponse")]
        UsuarioCRUD.WSArea.helloResponse hello(UsuarioCRUD.WSArea.helloRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://calculadora.service.ed.com/CalculadoraArea/helloRequest", ReplyAction="http://calculadora.service.ed.com/CalculadoraArea/helloResponse")]
        System.Threading.Tasks.Task<UsuarioCRUD.WSArea.helloResponse> helloAsync(UsuarioCRUD.WSArea.helloRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AreaCuadrado", WrapperNamespace="http://calculadora.service.ed.com/", IsWrapped=true)]
    public partial class AreaCuadradoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double arg0;
        
        public AreaCuadradoRequest() {
        }
        
        public AreaCuadradoRequest(double arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AreaCuadradoResponse", WrapperNamespace="http://calculadora.service.ed.com/", IsWrapped=true)]
    public partial class AreaCuadradoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double @return;
        
        public AreaCuadradoResponse() {
        }
        
        public AreaCuadradoResponse(double @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AreaRectangulo", WrapperNamespace="http://calculadora.service.ed.com/", IsWrapped=true)]
    public partial class AreaRectanguloRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public double arg1;
        
        public AreaRectanguloRequest() {
        }
        
        public AreaRectanguloRequest(double arg0, double arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AreaRectanguloResponse", WrapperNamespace="http://calculadora.service.ed.com/", IsWrapped=true)]
    public partial class AreaRectanguloResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double @return;
        
        public AreaRectanguloResponse() {
        }
        
        public AreaRectanguloResponse(double @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AreaTriangulo", WrapperNamespace="http://calculadora.service.ed.com/", IsWrapped=true)]
    public partial class AreaTrianguloRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public double arg1;
        
        public AreaTrianguloRequest() {
        }
        
        public AreaTrianguloRequest(double arg0, double arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AreaTrianguloResponse", WrapperNamespace="http://calculadora.service.ed.com/", IsWrapped=true)]
    public partial class AreaTrianguloResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double @return;
        
        public AreaTrianguloResponse() {
        }
        
        public AreaTrianguloResponse(double @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AreaCirculo", WrapperNamespace="http://calculadora.service.ed.com/", IsWrapped=true)]
    public partial class AreaCirculoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double arg0;
        
        public AreaCirculoRequest() {
        }
        
        public AreaCirculoRequest(double arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AreaCirculoResponse", WrapperNamespace="http://calculadora.service.ed.com/", IsWrapped=true)]
    public partial class AreaCirculoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double @return;
        
        public AreaCirculoResponse() {
        }
        
        public AreaCirculoResponse(double @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class helloRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="hello", Namespace="http://calculadora.service.ed.com/", Order=0)]
        public UsuarioCRUD.WSArea.helloRequestBody Body;
        
        public helloRequest() {
        }
        
        public helloRequest(UsuarioCRUD.WSArea.helloRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class helloRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        public helloRequestBody() {
        }
        
        public helloRequestBody(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class helloResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="helloResponse", Namespace="http://calculadora.service.ed.com/", Order=0)]
        public UsuarioCRUD.WSArea.helloResponseBody Body;
        
        public helloResponse() {
        }
        
        public helloResponse(UsuarioCRUD.WSArea.helloResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class helloResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public helloResponseBody() {
        }
        
        public helloResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CalculadoraAreaChannel : UsuarioCRUD.WSArea.CalculadoraArea, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CalculadoraAreaClient : System.ServiceModel.ClientBase<UsuarioCRUD.WSArea.CalculadoraArea>, UsuarioCRUD.WSArea.CalculadoraArea {
        
        public CalculadoraAreaClient() {
        }
        
        public CalculadoraAreaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CalculadoraAreaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculadoraAreaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculadoraAreaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UsuarioCRUD.WSArea.AreaCuadradoResponse UsuarioCRUD.WSArea.CalculadoraArea.AreaCuadrado(UsuarioCRUD.WSArea.AreaCuadradoRequest request) {
            return base.Channel.AreaCuadrado(request);
        }
        
        public double AreaCuadrado(double arg0) {
            UsuarioCRUD.WSArea.AreaCuadradoRequest inValue = new UsuarioCRUD.WSArea.AreaCuadradoRequest();
            inValue.arg0 = arg0;
            UsuarioCRUD.WSArea.AreaCuadradoResponse retVal = ((UsuarioCRUD.WSArea.CalculadoraArea)(this)).AreaCuadrado(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UsuarioCRUD.WSArea.AreaCuadradoResponse> UsuarioCRUD.WSArea.CalculadoraArea.AreaCuadradoAsync(UsuarioCRUD.WSArea.AreaCuadradoRequest request) {
            return base.Channel.AreaCuadradoAsync(request);
        }
        
        public System.Threading.Tasks.Task<UsuarioCRUD.WSArea.AreaCuadradoResponse> AreaCuadradoAsync(double arg0) {
            UsuarioCRUD.WSArea.AreaCuadradoRequest inValue = new UsuarioCRUD.WSArea.AreaCuadradoRequest();
            inValue.arg0 = arg0;
            return ((UsuarioCRUD.WSArea.CalculadoraArea)(this)).AreaCuadradoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UsuarioCRUD.WSArea.AreaRectanguloResponse UsuarioCRUD.WSArea.CalculadoraArea.AreaRectangulo(UsuarioCRUD.WSArea.AreaRectanguloRequest request) {
            return base.Channel.AreaRectangulo(request);
        }
        
        public double AreaRectangulo(double arg0, double arg1) {
            UsuarioCRUD.WSArea.AreaRectanguloRequest inValue = new UsuarioCRUD.WSArea.AreaRectanguloRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            UsuarioCRUD.WSArea.AreaRectanguloResponse retVal = ((UsuarioCRUD.WSArea.CalculadoraArea)(this)).AreaRectangulo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UsuarioCRUD.WSArea.AreaRectanguloResponse> UsuarioCRUD.WSArea.CalculadoraArea.AreaRectanguloAsync(UsuarioCRUD.WSArea.AreaRectanguloRequest request) {
            return base.Channel.AreaRectanguloAsync(request);
        }
        
        public System.Threading.Tasks.Task<UsuarioCRUD.WSArea.AreaRectanguloResponse> AreaRectanguloAsync(double arg0, double arg1) {
            UsuarioCRUD.WSArea.AreaRectanguloRequest inValue = new UsuarioCRUD.WSArea.AreaRectanguloRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((UsuarioCRUD.WSArea.CalculadoraArea)(this)).AreaRectanguloAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UsuarioCRUD.WSArea.AreaTrianguloResponse UsuarioCRUD.WSArea.CalculadoraArea.AreaTriangulo(UsuarioCRUD.WSArea.AreaTrianguloRequest request) {
            return base.Channel.AreaTriangulo(request);
        }
        
        public double AreaTriangulo(double arg0, double arg1) {
            UsuarioCRUD.WSArea.AreaTrianguloRequest inValue = new UsuarioCRUD.WSArea.AreaTrianguloRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            UsuarioCRUD.WSArea.AreaTrianguloResponse retVal = ((UsuarioCRUD.WSArea.CalculadoraArea)(this)).AreaTriangulo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UsuarioCRUD.WSArea.AreaTrianguloResponse> UsuarioCRUD.WSArea.CalculadoraArea.AreaTrianguloAsync(UsuarioCRUD.WSArea.AreaTrianguloRequest request) {
            return base.Channel.AreaTrianguloAsync(request);
        }
        
        public System.Threading.Tasks.Task<UsuarioCRUD.WSArea.AreaTrianguloResponse> AreaTrianguloAsync(double arg0, double arg1) {
            UsuarioCRUD.WSArea.AreaTrianguloRequest inValue = new UsuarioCRUD.WSArea.AreaTrianguloRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((UsuarioCRUD.WSArea.CalculadoraArea)(this)).AreaTrianguloAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UsuarioCRUD.WSArea.AreaCirculoResponse UsuarioCRUD.WSArea.CalculadoraArea.AreaCirculo(UsuarioCRUD.WSArea.AreaCirculoRequest request) {
            return base.Channel.AreaCirculo(request);
        }
        
        public double AreaCirculo(double arg0) {
            UsuarioCRUD.WSArea.AreaCirculoRequest inValue = new UsuarioCRUD.WSArea.AreaCirculoRequest();
            inValue.arg0 = arg0;
            UsuarioCRUD.WSArea.AreaCirculoResponse retVal = ((UsuarioCRUD.WSArea.CalculadoraArea)(this)).AreaCirculo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UsuarioCRUD.WSArea.AreaCirculoResponse> UsuarioCRUD.WSArea.CalculadoraArea.AreaCirculoAsync(UsuarioCRUD.WSArea.AreaCirculoRequest request) {
            return base.Channel.AreaCirculoAsync(request);
        }
        
        public System.Threading.Tasks.Task<UsuarioCRUD.WSArea.AreaCirculoResponse> AreaCirculoAsync(double arg0) {
            UsuarioCRUD.WSArea.AreaCirculoRequest inValue = new UsuarioCRUD.WSArea.AreaCirculoRequest();
            inValue.arg0 = arg0;
            return ((UsuarioCRUD.WSArea.CalculadoraArea)(this)).AreaCirculoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UsuarioCRUD.WSArea.helloResponse UsuarioCRUD.WSArea.CalculadoraArea.hello(UsuarioCRUD.WSArea.helloRequest request) {
            return base.Channel.hello(request);
        }
        
        public string hello(string name) {
            UsuarioCRUD.WSArea.helloRequest inValue = new UsuarioCRUD.WSArea.helloRequest();
            inValue.Body = new UsuarioCRUD.WSArea.helloRequestBody();
            inValue.Body.name = name;
            UsuarioCRUD.WSArea.helloResponse retVal = ((UsuarioCRUD.WSArea.CalculadoraArea)(this)).hello(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UsuarioCRUD.WSArea.helloResponse> UsuarioCRUD.WSArea.CalculadoraArea.helloAsync(UsuarioCRUD.WSArea.helloRequest request) {
            return base.Channel.helloAsync(request);
        }
        
        public System.Threading.Tasks.Task<UsuarioCRUD.WSArea.helloResponse> helloAsync(string name) {
            UsuarioCRUD.WSArea.helloRequest inValue = new UsuarioCRUD.WSArea.helloRequest();
            inValue.Body = new UsuarioCRUD.WSArea.helloRequestBody();
            inValue.Body.name = name;
            return ((UsuarioCRUD.WSArea.CalculadoraArea)(this)).helloAsync(inValue);
        }
    }
}
